orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login, name="login"),
    path("registrarse",views.registro, name="registro"),
    path("menu",views.menu, name="menu"),
    path("detalles_pizza", views.detalles_pizza, name="detalles_pizza"),
]

pizza/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("orders.urls")),
    path("admin/", admin.site.urls),
]

orders/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.conf import settings

User = get_user_model() #Toma le modelo del ususario que vamos a crear

# Create your models here.
class Toppings(models.Model):
    nombre = models.CharField(max_length=35)
    precio = models.DecimalField(max_digits=4,null=True, blank=True, default=00.00, decimal_places=2)

    def _str_(self):
        return f"(self.nombre)"

class menu(models.Model):
    categorias= (
        ('pizza', 'pizza'),
        ('pasta', 'pasta'),
        ('Dinner Platters', 'Dinner PLatters'),
    )

    tamano = (
        ('SM', 'Small'),
        ('L', 'Large'),
    )

    nombre = models.CharField(max_length=35, null=True, blank=True)

    categoria = models.CharField(max_length =15, null=True,blank=True, choices= categorias) #Choices le estamos diciendo que escoja entre las opciones del diccionario categorias

    precio = models.DecimalField(max_digits=4, null=True, blank=True, decimal_places=2, default=0.00)

    tamano = models.CharField(max_length =30, null=True,blank=True, choices= tamano)

    toppings = models.CharField(max_length =30, null=True,blank=True)

    cantidad_toppings = models.CharField(max_length =30, null=True,blank=True)

    def __str__ (self):
        return f"Categoria:{self.nombre} - {self.categoria} - {self.precio} - {self.tamano} - {self.toppings} - {self.cantidad_toppings}"

class user(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    menu = models.ManyToManyField(menu, blank=True)

    def __str__(self):
        return f"{self.user}"

def create_user(sender, instance, created, *args, **kwargs):
    if created:
        user_profile, created = user.objects.get_or_create(user = instance)

post_save.connect(create_user, sender=settings.AUTH_USER_MODEL)

orders/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.models import User


# Create your views here.
def index(request):
    return render(request,"login.html")

# Create your views here.
def login(request):
    return HttpResponse("Project 3: TODO")

def registro(request):
    if request.method == "POST":
        username = request.POST["usuario"]
        nombre = request.POST["nombre"]
        apellido = request.POST["apellido"]
        password = request.POST["password"]   
        email = request.POST["email"]

        User.objects.create_user(username,nombre,apellido,password,email)

        return HttpResponse("ingresado")

        #return render(request)

    return render(request,"orders/registrarse.html")

def menu(request):
    return render(request,"menu.html")
def detalles_pizza(request):
    return render(request,"detalles_pizza.html")

orders/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="login.css">
</head>
<body>
        
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:700,600' rel='stylesheet' type='text/css'>

    <form method="post" action="index.html">
    <div class="box">
    <h1>Dashboard</h1>
        
    <input type="email" name="email" value="email" onFocus="field_focus(this, 'email');" onblur="field_blur(this, 'email');" class="email" />
          
    <input type="password" name="email" value="email" onFocus="field_focus(this, 'email');" onblur="field_blur(this, 'email');" class="email" />
          
    <a href="#"><div class="btn">Sign In</div></a> <!-- End Btn -->
        
    <a href="#"><div id="btn2">Sign Up</div></a> <!-- End Btn2 -->
          
    </div> <!-- End Box -->
          
    </form>
        
    <p>Forgot your password? <u style="color:#f1c40f;">Click Here!</u></p>
          
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js" type="text/javascript"></script>
</body>
</html>

orders/templates/orders/detalles_pizza.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pizza Regular</title>

    <style>
        .topping-options {
            display: none;
        }
    </style>

    <script>
        function mostrarToppings() {
            console.log("Función mostrarToppings llamada.");  // Agregado para verificar la llamada en la consola
            var opcion = document.getElementById("opciones").value;
            var contenedorToppings = document.getElementById("contenedorToppings");

            // Ocultar todos los campos de toppings
            var toppings = contenedorToppings.getElementsByClassName("topping-options");
            for (var i = 0; i < toppings.length; i++) {
                toppings[i].style.display = "none";
            }

            // Mostrar la cantidad de campos de toppings según la opción seleccionada
            for (var i = 1; i <= opcion; i++) {
                var campoTopping = document.getElementById("topping" + i + "Field");
                campoTopping.style.display = "block";
            }
        }

        // Llama a la función inicialmente para configurar los campos de topping
        window.onload = mostrarToppings;
    </script>
    </head>
<body>
    <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
         <a class="navbar-brand" href="#">Añada a su pedido</a>+
        </div>   
    </nav>
    <div class="container text-center">
        <div class="row">
            <div class="col">
              <h4>Detalles</h4>
              <form action="/procesar_pedido" method="post">
                <!-- Campo para seleccionar el tamaño de la pizza -->
                <label for="tamanio">Tamaño de la Pizza:</label>
                <select id="tamanio" name="tamanio" required>
                    <option value="Small">Small</option>
                    <option value="mediana">Grande</option>
                </select>
        
                <label for="opciones">Opciones de Pizza:</label>
                <select id="opciones" name="opciones" onchange="mostrarToppings()" required>
                    <option value="cheese">Cheese</option>
                    <option value="1topping">1 Topping</option>
                    <option value="2toppings">2 Toppings</option>
                    <option value="3toppings">3 Toppings</option>
                    <option value="special">Special</option>
                </select>
        
                <br>
        
                <div id="contenedorToppings">
                    <!-- Campo de toppings 1 -->
                    <div id="topping1Field" class="topping-options">
                        <label for="topping1">Topping 1:</label>
                        <input type="text" id="topping1" name="topping1" required>
                    </div>
        
                    <!-- Campo de toppings 2 -->
                    <div id="topping2Field" class="topping-options">
                        <label for="topping2">Topping 2:</label>
                        <input type="text" id="topping2" name="topping2" required>
                    </div>
        
                    <!-- Campo de toppings 3 -->
                    <div id="topping3Field" class="topping-options">
                        <label for="topping3">Topping 3:</label>
                        <input type="text" id="topping3" name="topping3" required>
                    </div>
                </div>
        
                <br>
        
                <button type="submit">Añadir al carrito</button>
            </form>
        </div>
    </div>
</div>
</body>
</html>

orders/templates/orders/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="login.css">
</head>
<body>
        
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:700,600' rel='stylesheet' type='text/css'>

    <form method="post" action="index.html">
    <div class="box">
    <h1>Dashboard</h1>
        
    <input type="email" name="email" value="email" onFocus="field_focus(this, 'email');" onblur="field_blur(this, 'email');" class="email" />
          
    <input type="password" name="email" value="email" onFocus="field_focus(this, 'email');" onblur="field_blur(this, 'email');" class="email" />
          
    <a href="#"><div class="btn">Sign In</div></a> <!-- End Btn -->
        
    <a href="{% url 'registro' %}"><div id="btn2">Sign Up</div></a> <!-- End Btn2 -->
          
    </div> <!-- End Box -->
          
    </form>
        
    <p>Forgot your password? <u style="color:#f1c40f;">Click Here!</u></p>
          
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js" type="text/javascript"></script>
</body>
</html>

orders/templates/orders/menu.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <enlace rel=”hoja de estilo” href=”https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css”></enlace>

    <title>Menu</title>
</head>
<body>

    <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Bienvenido a la pizzeria</a>
        </div>
      </nav>

    <h3>Seleccione su comida</h3>  

      <div class="container" align="right">
        <p>
            <button type="button" 
                class="btn btn-default btn-sm">
                <span class="glyphicon 
                    glyphicon-shopping-cart">
                </span>
                <b> Add to Cart </b>
            </button>
        </p>
    </div>

    <div class="container text-center">
        <div class="row">
          <div class="col">
            <img src="{% static 'static/regular_pizza.jpg' %}" class="img-responsive" alt="Descripción de la imagen">
            Regular Pizza
          </div>
          <div class="col">
            Sicilian Pizza
          </div>
          <div class="col">
            Pasta
          </div>
        </div>
        <div class="row">
            <div class="col">
              Salad
            </div>
            <div class="col">
              Dinners Plate
            </div>
          </div>
      </div>
    
    <script src=”https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js”></script>
    <script src=”https://maxcdn.bootstrapcdn.com /bootstrap/3.4.0/js/bootstrap.min.js”> </script>
    <span class=”glyphicon glyphicon-carrito-de-compras”> </span>
</body>
</html>

orders/templates/orders/registrarse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro</title>
</head>
<body>
    <h1>Registro</h1>
    <form action="{% url 'orders:registro' %}">
        <input placeholder="Username" name="usuario" type="text">
        <input placeholder="First Name" name="nombre" type="text">
        <input placeholder="Last Name" name="apellido" type="text">
        <input placeholder="Password" name="password" type="text">
        <input placeholder="Email" name="email" type="text">
        <button type="submit">Insertar</button>
    </form>
</body>
</html>

orders/templates/registrarse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro</title>
</head>
<body>
    <h1>Registro</h1>
    <form>
        <input placeholder="Username" name="nombre" type="text">
        <input placeholder="First Name" name="nombre" type="text">
        <input placeholder="Last Name" name="password" type="text">
        <input placeholder="Password" name="password" type="text">
        <input placeholder="Email" name="email" type="text">
        <button>Insertar</button>
    </form>
</body>
</html>